apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-ts-train
  namespace: chaos-mesh
spec:
  mode: all
  selector:
    namespaces:
      - ts
    labelSelectors:
      app: ts-train-service
  stressors:
    cpu:
      workers: 4
      load: 100
  duration: "3m"
